### ISSUE TITLE
Manual connection adjustments 

### ISSUE THREAD

**Issue by wardru** [Panduza/panduza_sandbox_flutter#10]
Manual Connection works great but there are some bugs/remarks that we should take care of:

1. The form mentions a Platform name, it should be a Connection name. You can have many platforms behind this connection. Here you connect to a broker, so what you are creating is a connection to a broker.

2. You shouldn't be able to create a connection if any of the fields is empty.

3. We should check that another connection with the same name doesn't exist already.

4. We should check that another connection with a different name doesn't already have the same IP and port.

5. We should check that the port is a number (it gives an error right now ```flutter: FormatException: Invalid radix-10 number (at character 1)```)

**Comment by Darcraytore1** [comment]
I already have add these checks in the two last commit of the PR Model view change with workflow (https://github.com/Panduza/panduza_sandbox_flutter/pull/6) who has already been merged in main

**Comment by wardru** [comment]
Indeed, but there is a missing check on the port that I didn't mention earlier.
I can pass a negative port which makes no sense. TCP/UDP port range is a 16bit unsigned integer.
