### ISSUE TITLE
Inject version number with workflow 

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza_sandbox_flutter#7]
If possible, inject version number inside the application during workflow.
If build from tag, use the tag name.
Else use the branch name and the date of the day.

**Comment by Darcraytore1** [comment]
I used the sha of tag and branch instead of the name to create the version number and name because String are not accepted in it.

**Comment by XdoctorwhoZ** [comment]
Tag must respect only number and dot format

- Number for official release: 0.0.0
- Number for intermediate build: YEAR.MONTH.DAY.HOUR
