### ISSUE TITLE
Cannot create a localhost connection

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza_sandbox_flutter#73]
![image](https://github.com/Panduza/panduza_sandbox_flutter/assets/1451383/3a78c5e7-ab10-4377-9f79-387c5c679657)

**Comment by Darcraytore1** [comment]
I don't think so, but you don't already have a connection with localhost:1883 created ? I have tested it but I don't have this problem, this could be a problem with shared preference (data on the disk) again but this time I don't think so.
